name: Linting

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Run lint checks with Gradle Wrapper
        run: ./gradlew ktlintCheck

#  build-and-publish:
#    needs: linting
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Checkout project sources
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#          cache: 'gradle'
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          cache-read-only: false
#
#      - name: Build and package distribution
#        run: ./gradlew packageDistributionForCurrentOS
#
#      - name: Upload build artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: shake-${{ github.sha }}-${{ matrix.os }}
#          path: |
#            build/compose/binaries/*
