name: Publishing

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build and package distribution
        run: ./gradlew packageDistributionForCurrentOS
        env:
          VERSION: ${{ github.ref_name }}

      - name: Upload Platform-Specific Artifact
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "artifact_path=build/compose/binaries/main/dmg/*.dmg" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "artifact_path=build/compose/binaries/main/deb/*.deb" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "artifact_path=build/compose/binaries/main/msi/*.exe" >> $GITHUB_ENV
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shaker-${{ github.ref_name }}-${{ matrix.os }}
          path: ${{ env.artifact_path }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: shaker-${{ github.ref_name }}-ubuntu-latest
          path: linux_artifacts

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: shaker-${{ github.ref_name }}-macos-latest
          path: macos_artifacts

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: shaker-${{ github.ref_name }}-windows-latest
          path: windows_artifacts

      - name: Publish artifacts to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          artifacts: |
            linux_artifacts/*.deb, 
            macos_artifacts/*.dmg, 
            windows_artifacts/*.exe
          tag: ${{ github.ref_name }}
          body: |
            This release includes builds for Linux (.deb), macOS (.dmg), and Windows (.exe).
 
